// Code generated by protoc-gen-go. DO NOT EDIT.
// source: goods.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GoodsModel struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Price                float64  `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoodsModel) Reset()         { *m = GoodsModel{} }
func (m *GoodsModel) String() string { return proto.CompactTextString(m) }
func (*GoodsModel) ProtoMessage()    {}
func (*GoodsModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_a30593c5487368b0, []int{0}
}

func (m *GoodsModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoodsModel.Unmarshal(m, b)
}
func (m *GoodsModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoodsModel.Marshal(b, m, deterministic)
}
func (m *GoodsModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoodsModel.Merge(m, src)
}
func (m *GoodsModel) XXX_Size() int {
	return xxx_messageInfo_GoodsModel.Size(m)
}
func (m *GoodsModel) XXX_DiscardUnknown() {
	xxx_messageInfo_GoodsModel.DiscardUnknown(m)
}

var xxx_messageInfo_GoodsModel proto.InternalMessageInfo

func (m *GoodsModel) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GoodsModel) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *GoodsModel) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type AddGoodsReq struct {
	Result               *GoodsModel `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AddGoodsReq) Reset()         { *m = AddGoodsReq{} }
func (m *AddGoodsReq) String() string { return proto.CompactTextString(m) }
func (*AddGoodsReq) ProtoMessage()    {}
func (*AddGoodsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a30593c5487368b0, []int{1}
}

func (m *AddGoodsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddGoodsReq.Unmarshal(m, b)
}
func (m *AddGoodsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddGoodsReq.Marshal(b, m, deterministic)
}
func (m *AddGoodsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddGoodsReq.Merge(m, src)
}
func (m *AddGoodsReq) XXX_Size() int {
	return xxx_messageInfo_AddGoodsReq.Size(m)
}
func (m *AddGoodsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddGoodsReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddGoodsReq proto.InternalMessageInfo

func (m *AddGoodsReq) GetResult() *GoodsModel {
	if m != nil {
		return m.Result
	}
	return nil
}

type AddGoodsRes struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddGoodsRes) Reset()         { *m = AddGoodsRes{} }
func (m *AddGoodsRes) String() string { return proto.CompactTextString(m) }
func (*AddGoodsRes) ProtoMessage()    {}
func (*AddGoodsRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_a30593c5487368b0, []int{2}
}

func (m *AddGoodsRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddGoodsRes.Unmarshal(m, b)
}
func (m *AddGoodsRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddGoodsRes.Marshal(b, m, deterministic)
}
func (m *AddGoodsRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddGoodsRes.Merge(m, src)
}
func (m *AddGoodsRes) XXX_Size() int {
	return xxx_messageInfo_AddGoodsRes.Size(m)
}
func (m *AddGoodsRes) XXX_DiscardUnknown() {
	xxx_messageInfo_AddGoodsRes.DiscardUnknown(m)
}

var xxx_messageInfo_AddGoodsRes proto.InternalMessageInfo

func (m *AddGoodsRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AddGoodsRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetGoodsReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGoodsReq) Reset()         { *m = GetGoodsReq{} }
func (m *GetGoodsReq) String() string { return proto.CompactTextString(m) }
func (*GetGoodsReq) ProtoMessage()    {}
func (*GetGoodsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a30593c5487368b0, []int{3}
}

func (m *GetGoodsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGoodsReq.Unmarshal(m, b)
}
func (m *GetGoodsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGoodsReq.Marshal(b, m, deterministic)
}
func (m *GetGoodsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGoodsReq.Merge(m, src)
}
func (m *GetGoodsReq) XXX_Size() int {
	return xxx_messageInfo_GetGoodsReq.Size(m)
}
func (m *GetGoodsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGoodsReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetGoodsReq proto.InternalMessageInfo

func (m *GetGoodsReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetGoodsRes struct {
	GoodsList            []*GoodsModel `protobuf:"bytes,1,rep,name=goodsList,proto3" json:"goodsList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetGoodsRes) Reset()         { *m = GetGoodsRes{} }
func (m *GetGoodsRes) String() string { return proto.CompactTextString(m) }
func (*GetGoodsRes) ProtoMessage()    {}
func (*GetGoodsRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_a30593c5487368b0, []int{4}
}

func (m *GetGoodsRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGoodsRes.Unmarshal(m, b)
}
func (m *GetGoodsRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGoodsRes.Marshal(b, m, deterministic)
}
func (m *GetGoodsRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGoodsRes.Merge(m, src)
}
func (m *GetGoodsRes) XXX_Size() int {
	return xxx_messageInfo_GetGoodsRes.Size(m)
}
func (m *GetGoodsRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGoodsRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetGoodsRes proto.InternalMessageInfo

func (m *GetGoodsRes) GetGoodsList() []*GoodsModel {
	if m != nil {
		return m.GoodsList
	}
	return nil
}

func init() {
	proto.RegisterType((*GoodsModel)(nil), "goodsService.GoodsModel")
	proto.RegisterType((*AddGoodsReq)(nil), "goodsService.AddGoodsReq")
	proto.RegisterType((*AddGoodsRes)(nil), "goodsService.AddGoodsRes")
	proto.RegisterType((*GetGoodsReq)(nil), "goodsService.GetGoodsReq")
	proto.RegisterType((*GetGoodsRes)(nil), "goodsService.GetGoodsRes")
}

func init() {
	proto.RegisterFile("goods.proto", fileDescriptor_a30593c5487368b0)
}

var fileDescriptor_a30593c5487368b0 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x49, 0x4a, 0xff, 0x64, 0x22, 0x1e, 0x16, 0x0f, 0x31, 0x20, 0x96, 0x9c, 0x7a, 0x4a,
	0xa5, 0x82, 0x57, 0xad, 0x20, 0xbd, 0xe8, 0x65, 0xbd, 0x79, 0xab, 0xbb, 0x63, 0x58, 0x48, 0xba,
	0x31, 0xb3, 0xf1, 0x83, 0xf8, 0x89, 0x65, 0x37, 0x5d, 0xbb, 0x15, 0xea, 0x29, 0xbc, 0xbc, 0x37,
	0x6f, 0x7e, 0x99, 0x40, 0x5a, 0x69, 0x2d, 0xa9, 0x6c, 0x3b, 0x6d, 0x34, 0x3b, 0x73, 0xe2, 0x15,
	0xbb, 0x2f, 0x25, 0x30, 0xbf, 0xae, 0xb4, 0xae, 0x6a, 0x5c, 0x3a, 0xef, 0xbd, 0xff, 0x58, 0x1a,
	0xd5, 0x20, 0x99, 0x6d, 0xd3, 0x0e, 0xf1, 0x82, 0x03, 0x6c, 0xec, 0xc0, 0x8b, 0x96, 0x58, 0xb3,
	0x0b, 0x18, 0x1b, 0x65, 0x6a, 0xcc, 0xa2, 0x79, 0xb4, 0x48, 0xf8, 0x20, 0xec, 0xdb, 0xb6, 0x53,
	0x02, 0xb3, 0x78, 0x1e, 0x2d, 0x22, 0x3e, 0x08, 0x96, 0xc1, 0x54, 0xe8, 0x9d, 0xc1, 0x9d, 0xc9,
	0x46, 0x2e, 0xed, 0x65, 0x71, 0x0f, 0xe9, 0x5a, 0x4a, 0x57, 0xcb, 0xf1, 0x93, 0xdd, 0xc0, 0xa4,
	0x43, 0xea, 0x6b, 0xe3, 0x5a, 0xd3, 0x55, 0x56, 0x86, 0x88, 0xe5, 0x61, 0x3d, 0xdf, 0xe7, 0x8a,
	0x75, 0x58, 0x40, 0x76, 0x53, 0x83, 0x44, 0xdb, 0xca, 0x73, 0x79, 0x69, 0x1d, 0xea, 0x85, 0x40,
	0x22, 0xc7, 0x36, 0xe3, 0x5e, 0x16, 0x57, 0x90, 0x6e, 0xd0, 0xfc, 0x32, 0x9c, 0x43, 0xac, 0xa4,
	0x9b, 0x1e, 0xf3, 0x58, 0xc9, 0xe2, 0x29, 0xb4, 0x89, 0xdd, 0x41, 0xe2, 0x98, 0x9e, 0x15, 0x59,
	0xca, 0xd1, 0xbf, 0x94, 0x87, 0xe8, 0xea, 0x3b, 0x82, 0xa3, 0x7b, 0xb3, 0x07, 0x98, 0x79, 0x72,
	0x76, 0x79, 0xdc, 0x10, 0x9c, 0x24, 0x3f, 0x69, 0x91, 0x6d, 0xf0, 0x64, 0x7f, 0x1b, 0x82, 0x0f,
	0xca, 0x4f, 0x5b, 0x8f, 0xc9, 0xdb, 0xb4, 0xdc, 0xff, 0xf0, 0x89, 0x7b, 0xdc, 0xfe, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x6d, 0x57, 0x9b, 0x92, 0x22, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GoodsServiceClient is the client API for GoodsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GoodsServiceClient interface {
	AddGoods(ctx context.Context, in *AddGoodsReq, opts ...grpc.CallOption) (*AddGoodsRes, error)
	GetGoods(ctx context.Context, in *GetGoodsReq, opts ...grpc.CallOption) (*GetGoodsReq, error)
}

type goodsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGoodsServiceClient(cc grpc.ClientConnInterface) GoodsServiceClient {
	return &goodsServiceClient{cc}
}

func (c *goodsServiceClient) AddGoods(ctx context.Context, in *AddGoodsReq, opts ...grpc.CallOption) (*AddGoodsRes, error) {
	out := new(AddGoodsRes)
	err := c.cc.Invoke(ctx, "/goodsService.goodsService/AddGoods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsServiceClient) GetGoods(ctx context.Context, in *GetGoodsReq, opts ...grpc.CallOption) (*GetGoodsReq, error) {
	out := new(GetGoodsReq)
	err := c.cc.Invoke(ctx, "/goodsService.goodsService/GetGoods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoodsServiceServer is the server API for GoodsService service.
type GoodsServiceServer interface {
	AddGoods(context.Context, *AddGoodsReq) (*AddGoodsRes, error)
	GetGoods(context.Context, *GetGoodsReq) (*GetGoodsReq, error)
}

// UnimplementedGoodsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGoodsServiceServer struct {
}

func (*UnimplementedGoodsServiceServer) AddGoods(ctx context.Context, req *AddGoodsReq) (*AddGoodsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddGoods not implemented")
}
func (*UnimplementedGoodsServiceServer) GetGoods(ctx context.Context, req *GetGoodsReq) (*GetGoodsReq, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGoods not implemented")
}

func RegisterGoodsServiceServer(s *grpc.Server, srv GoodsServiceServer) {
	s.RegisterService(&_GoodsService_serviceDesc, srv)
}

func _GoodsService_AddGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGoodsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServiceServer).AddGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goodsService.goodsService/AddGoods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServiceServer).AddGoods(ctx, req.(*AddGoodsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsService_GetGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGoodsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServiceServer).GetGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goodsService.goodsService/GetGoods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServiceServer).GetGoods(ctx, req.(*GetGoodsReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _GoodsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "goodsService.goodsService",
	HandlerType: (*GoodsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddGoods",
			Handler:    _GoodsService_AddGoods_Handler,
		},
		{
			MethodName: "GetGoods",
			Handler:    _GoodsService_GetGoods_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goods.proto",
}
