// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orderInfo.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Order struct {
	Id                   int64            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Price                float64          `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Name                 string           `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Tel                  string           `protobuf:"bytes,4,opt,name=tel,proto3" json:"tel,omitempty"`
	Address              string           `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	AddTime              string           `protobuf:"bytes,6,opt,name=addTime,proto3" json:"addTime,omitempty"`
	Orderitem            *Order_OrderItem `protobuf:"bytes,7,opt,name=Orderitem,proto3" json:"Orderitem,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e838811beff491e, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Order) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Order) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Order) GetTel() string {
	if m != nil {
		return m.Tel
	}
	return ""
}

func (m *Order) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Order) GetAddTime() string {
	if m != nil {
		return m.AddTime
	}
	return ""
}

func (m *Order) GetOrderitem() *Order_OrderItem {
	if m != nil {
		return m.Orderitem
	}
	return nil
}

type Order_OrderItem struct {
	GoodsId              int64    `protobuf:"varint,1,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Price                float64  `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Num                  int32    `protobuf:"varint,4,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order_OrderItem) Reset()         { *m = Order_OrderItem{} }
func (m *Order_OrderItem) String() string { return proto.CompactTextString(m) }
func (*Order_OrderItem) ProtoMessage()    {}
func (*Order_OrderItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e838811beff491e, []int{0, 0}
}

func (m *Order_OrderItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order_OrderItem.Unmarshal(m, b)
}
func (m *Order_OrderItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order_OrderItem.Marshal(b, m, deterministic)
}
func (m *Order_OrderItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order_OrderItem.Merge(m, src)
}
func (m *Order_OrderItem) XXX_Size() int {
	return xxx_messageInfo_Order_OrderItem.Size(m)
}
func (m *Order_OrderItem) XXX_DiscardUnknown() {
	xxx_messageInfo_Order_OrderItem.DiscardUnknown(m)
}

var xxx_messageInfo_Order_OrderItem proto.InternalMessageInfo

func (m *Order_OrderItem) GetGoodsId() int64 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

func (m *Order_OrderItem) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Order_OrderItem) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Order_OrderItem) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func init() {
	proto.RegisterType((*Order)(nil), "orderService.Order")
	proto.RegisterType((*Order_OrderItem)(nil), "orderService.Order.OrderItem")
}

func init() {
	proto.RegisterFile("orderInfo.proto", fileDescriptor_2e838811beff491e)
}

var fileDescriptor_2e838811beff491e = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xbf, 0x4f, 0x84, 0x30,
	0x14, 0xc7, 0x53, 0x38, 0x8e, 0xf0, 0x34, 0x7a, 0x69, 0x1c, 0x9a, 0x4b, 0x8c, 0xc4, 0x89, 0x89,
	0x4b, 0x74, 0x74, 0x73, 0x63, 0x32, 0xa9, 0x4e, 0x6e, 0x48, 0xdf, 0x91, 0x26, 0x94, 0x92, 0xd2,
	0xf3, 0x7f, 0xf2, 0xbf, 0x34, 0x7d, 0x85, 0xbb, 0x5b, 0xe0, 0xfb, 0xe3, 0xbd, 0xb4, 0x9f, 0xc2,
	0xbd, 0x75, 0x0a, 0x5d, 0x33, 0x1e, 0x6d, 0x3d, 0x39, 0xeb, 0x2d, 0xbf, 0xa5, 0xe0, 0x13, 0xdd,
	0xaf, 0xee, 0x70, 0xff, 0xd4, 0x5b, 0xdb, 0x0f, 0x78, 0xa0, 0xee, 0xe7, 0x74, 0x3c, 0x78, 0x6d,
	0x70, 0xf6, 0xad, 0x99, 0xe2, 0xf8, 0xf3, 0x5f, 0x02, 0xd9, 0x47, 0xd8, 0xe0, 0x77, 0x90, 0x68,
	0x25, 0x58, 0xc9, 0xaa, 0x54, 0x26, 0x5a, 0xf1, 0x07, 0xc8, 0x26, 0xa7, 0x3b, 0x14, 0x49, 0xc9,
	0x2a, 0x26, 0xa3, 0xe1, 0x1c, 0x36, 0x63, 0x6b, 0x50, 0xa4, 0x25, 0xab, 0x0a, 0x49, 0x9a, 0xef,
	0x20, 0xf5, 0x38, 0x88, 0x0d, 0x45, 0x41, 0x72, 0x01, 0x79, 0xab, 0x94, 0xc3, 0x79, 0x16, 0x19,
	0xa5, 0xab, 0x5d, 0x9a, 0x2f, 0x6d, 0x50, 0x6c, 0xcf, 0x4d, 0xb0, 0xfc, 0x0d, 0x0a, 0xba, 0x88,
	0xf6, 0x68, 0x44, 0x5e, 0xb2, 0xea, 0xe6, 0xe5, 0xb1, 0xbe, 0x86, 0xa9, 0xa9, 0x8e, 0xdf, 0xc6,
	0xa3, 0x91, 0x97, 0xf9, 0x7d, 0xb7, 0x2c, 0x87, 0x3c, 0x9c, 0xd1, 0x5b, 0xab, 0xe6, 0x66, 0xc5,
	0x59, 0x6d, 0x60, 0xf2, 0xda, 0x0f, 0x91, 0xa9, 0x90, 0xd1, 0x5c, 0x48, 0xd3, 0x6b, 0xd2, 0x1d,
	0xa4, 0xe3, 0xc9, 0x10, 0x55, 0x26, 0x83, 0x7c, 0x2f, 0xbe, 0xf3, 0x7a, 0x79, 0xc9, 0x2d, 0xfd,
	0x5e, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0xbd, 0xc4, 0xe4, 0xf2, 0x7f, 0x01, 0x00, 0x00,
}
