// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userInfo.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PhoneType int32

const (
	PhoneType_MOBILE PhoneType = 0
	PhoneType_HOME   PhoneType = 1
	PhoneType_WORK   PhoneType = 2
)

var PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}

var PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x PhoneType) String() string {
	return proto.EnumName(PhoneType_name, int32(x))
}

func (PhoneType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9abb1e7c7c5082b5, []int{0}
}

type User struct {
	Id                   int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int64     `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Type                 PhoneType `protobuf:"varint,4,opt,name=type,proto3,enum=userService.PhoneType" json:"type,omitempty"`
	Hobby                []string  `protobuf:"bytes,5,rep,name=hobby,proto3" json:"hobby,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_9abb1e7c7c5082b5, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *User) GetType() PhoneType {
	if m != nil {
		return m.Type
	}
	return PhoneType_MOBILE
}

func (m *User) GetHobby() []string {
	if m != nil {
		return m.Hobby
	}
	return nil
}

func init() {
	proto.RegisterEnum("userService.PhoneType", PhoneType_name, PhoneType_value)
	proto.RegisterType((*User)(nil), "userService.User")
}

func init() {
	proto.RegisterFile("userInfo.proto", fileDescriptor_9abb1e7c7c5082b5)
}

var fileDescriptor_9abb1e7c7c5082b5 = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x51, 0x4b, 0xc3, 0x30,
	0x10, 0x80, 0x4d, 0x9b, 0x4d, 0x7b, 0x42, 0x29, 0x87, 0x48, 0xf0, 0xc5, 0xe2, 0x53, 0x99, 0x90,
	0x81, 0xfe, 0x83, 0xc1, 0xc0, 0xa1, 0xa3, 0x12, 0x15, 0xc1, 0xb7, 0xd6, 0xdd, 0xba, 0x80, 0x6d,
	0x42, 0x9a, 0x09, 0x7d, 0xf1, 0xb7, 0x4b, 0x33, 0x91, 0x3d, 0xdd, 0xf7, 0x71, 0x1f, 0x1c, 0x07,
	0xe9, 0xbe, 0x27, 0xb7, 0xea, 0xb6, 0x46, 0x5a, 0x67, 0xbc, 0xc1, 0xf3, 0xd1, 0x5f, 0xc8, 0x7d,
	0xeb, 0x4f, 0xba, 0xba, 0x6e, 0x8c, 0x69, 0xbe, 0x68, 0x1e, 0x56, 0xf5, 0x7e, 0x3b, 0xf7, 0xba,
	0xa5, 0xde, 0x57, 0xad, 0x3d, 0xd4, 0x37, 0x3f, 0xc0, 0xdf, 0x7a, 0x72, 0x98, 0x42, 0xa4, 0x37,
	0x82, 0xe5, 0xac, 0x88, 0x55, 0xa4, 0x37, 0x88, 0xc0, 0xbb, 0xaa, 0x25, 0x11, 0xe5, 0xac, 0x48,
	0x54, 0x60, 0xcc, 0x20, 0xae, 0x1a, 0x12, 0x71, 0x88, 0x46, 0xc4, 0x19, 0x70, 0x3f, 0x58, 0x12,
	0x3c, 0x67, 0x45, 0x7a, 0x77, 0x29, 0x8f, 0x4e, 0xcb, 0xe7, 0x9d, 0xe9, 0xe8, 0x75, 0xb0, 0xa4,
	0x42, 0x83, 0x17, 0x30, 0xd9, 0x99, 0xba, 0x1e, 0xc4, 0x24, 0x8f, 0x8b, 0x44, 0x1d, 0x64, 0x76,
	0x0b, 0xc9, 0x7f, 0x88, 0x00, 0xd3, 0x75, 0xb9, 0x58, 0x3d, 0x2d, 0xb3, 0x13, 0x3c, 0x03, 0xfe,
	0x50, 0xae, 0x97, 0x19, 0x1b, 0xe9, 0xbd, 0x54, 0x8f, 0x59, 0xb4, 0x48, 0x3e, 0x4e, 0xe5, 0xdf,
	0x2b, 0xd3, 0x30, 0xee, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xca, 0xfe, 0x3d, 0xa0, 0xfe, 0x00,
	0x00, 0x00,
}
