// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/shopping.proto

package microservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddToCartRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId            string   `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity             int32    `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddToCartRequest) Reset()         { *m = AddToCartRequest{} }
func (m *AddToCartRequest) String() string { return proto.CompactTextString(m) }
func (*AddToCartRequest) ProtoMessage()    {}
func (*AddToCartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3508a52b2f86acbc, []int{0}
}

func (m *AddToCartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddToCartRequest.Unmarshal(m, b)
}
func (m *AddToCartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddToCartRequest.Marshal(b, m, deterministic)
}
func (m *AddToCartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddToCartRequest.Merge(m, src)
}
func (m *AddToCartRequest) XXX_Size() int {
	return xxx_messageInfo_AddToCartRequest.Size(m)
}
func (m *AddToCartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddToCartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddToCartRequest proto.InternalMessageInfo

func (m *AddToCartRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AddToCartRequest) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *AddToCartRequest) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type AddToCartResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddToCartResponse) Reset()         { *m = AddToCartResponse{} }
func (m *AddToCartResponse) String() string { return proto.CompactTextString(m) }
func (*AddToCartResponse) ProtoMessage()    {}
func (*AddToCartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3508a52b2f86acbc, []int{1}
}

func (m *AddToCartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddToCartResponse.Unmarshal(m, b)
}
func (m *AddToCartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddToCartResponse.Marshal(b, m, deterministic)
}
func (m *AddToCartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddToCartResponse.Merge(m, src)
}
func (m *AddToCartResponse) XXX_Size() int {
	return xxx_messageInfo_AddToCartResponse.Size(m)
}
func (m *AddToCartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddToCartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddToCartResponse proto.InternalMessageInfo

func (m *AddToCartResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type CheckoutRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckoutRequest) Reset()         { *m = CheckoutRequest{} }
func (m *CheckoutRequest) String() string { return proto.CompactTextString(m) }
func (*CheckoutRequest) ProtoMessage()    {}
func (*CheckoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3508a52b2f86acbc, []int{2}
}

func (m *CheckoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckoutRequest.Unmarshal(m, b)
}
func (m *CheckoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckoutRequest.Marshal(b, m, deterministic)
}
func (m *CheckoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckoutRequest.Merge(m, src)
}
func (m *CheckoutRequest) XXX_Size() int {
	return xxx_messageInfo_CheckoutRequest.Size(m)
}
func (m *CheckoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckoutRequest proto.InternalMessageInfo

func (m *CheckoutRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type CheckoutResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	OrderId              string   `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckoutResponse) Reset()         { *m = CheckoutResponse{} }
func (m *CheckoutResponse) String() string { return proto.CompactTextString(m) }
func (*CheckoutResponse) ProtoMessage()    {}
func (*CheckoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3508a52b2f86acbc, []int{3}
}

func (m *CheckoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckoutResponse.Unmarshal(m, b)
}
func (m *CheckoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckoutResponse.Marshal(b, m, deterministic)
}
func (m *CheckoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckoutResponse.Merge(m, src)
}
func (m *CheckoutResponse) XXX_Size() int {
	return xxx_messageInfo_CheckoutResponse.Size(m)
}
func (m *CheckoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckoutResponse proto.InternalMessageInfo

func (m *CheckoutResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CheckoutResponse) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func init() {
	proto.RegisterType((*AddToCartRequest)(nil), "AddToCartRequest")
	proto.RegisterType((*AddToCartResponse)(nil), "AddToCartResponse")
	proto.RegisterType((*CheckoutRequest)(nil), "CheckoutRequest")
	proto.RegisterType((*CheckoutResponse)(nil), "CheckoutResponse")
}

func init() {
	proto.RegisterFile("proto/shopping.proto", fileDescriptor_3508a52b2f86acbc)
}

var fileDescriptor_3508a52b2f86acbc = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xa9, 0xe2, 0xda, 0xbe, 0x83, 0x6b, 0x83, 0x60, 0x2d, 0x08, 0xa3, 0xa7, 0x21, 0x98,
	0xc2, 0xfc, 0x0b, 0x74, 0x07, 0xe9, 0xb5, 0xf3, 0xe4, 0x45, 0x66, 0x12, 0x5d, 0x10, 0xfb, 0xb2,
	0xbc, 0x64, 0xe0, 0x7f, 0x2f, 0x4b, 0xb7, 0x29, 0xdd, 0x61, 0xc7, 0x4f, 0x5e, 0x78, 0xdf, 0x1f,
	0x0f, 0xae, 0x8c, 0x45, 0x87, 0x35, 0xad, 0xd0, 0x18, 0xdd, 0x7d, 0xf2, 0x80, 0xd5, 0x07, 0x64,
	0x8f, 0x52, 0xbe, 0xe0, 0x7c, 0x69, 0x5d, 0xab, 0xd6, 0x5e, 0x91, 0x63, 0xd7, 0x10, 0x7b, 0x52,
	0xf6, 0x4d, 0xcb, 0x22, 0x9a, 0x44, 0xd3, 0xb4, 0x1d, 0x6d, 0xb1, 0x91, 0xec, 0x16, 0xc0, 0x58,
	0x94, 0x5e, 0xb8, 0xed, 0xec, 0x2c, 0xcc, 0xd2, 0xdd, 0x4b, 0x23, 0x59, 0x09, 0xc9, 0xda, 0x2f,
	0x3b, 0xa7, 0xdd, 0x4f, 0x71, 0x3e, 0x89, 0xa6, 0x17, 0xed, 0x81, 0xab, 0x7b, 0xc8, 0xff, 0xe9,
	0x90, 0xc1, 0x8e, 0x14, 0x2b, 0x20, 0x26, 0x2f, 0x84, 0x22, 0x0a, 0x42, 0x49, 0xbb, 0xc7, 0xea,
	0x0e, 0xc6, 0xf3, 0x95, 0x12, 0x5f, 0xe8, 0x4f, 0xba, 0xaa, 0x9e, 0x21, 0xfb, 0xfb, 0x7b, 0x6a,
	0x33, 0xbb, 0x81, 0x04, 0xad, 0xec, 0xf7, 0xf4, 0x09, 0xe2, 0xc0, 0x8d, 0x9c, 0x6d, 0x60, 0xbc,
	0xd8, 0xb5, 0xb3, 0x50, 0x76, 0xa3, 0x85, 0x62, 0x33, 0x48, 0x0f, 0xb6, 0x59, 0xce, 0x87, 0x55,
	0x95, 0x8c, 0x1f, 0xa7, 0xaa, 0x21, 0xd9, 0xfb, 0x61, 0x19, 0x1f, 0xc4, 0x28, 0x73, 0x3e, 0x34,
	0xfb, 0x94, 0xbd, 0x5e, 0xf2, 0xfa, 0x5b, 0x0b, 0x8b, 0xd4, 0xcb, 0xbe, 0x8f, 0xc2, 0x71, 0x1e,
	0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xa5, 0x4f, 0xc3, 0x19, 0xb4, 0x01, 0x00, 0x00,
}
