version: '3.8'

services:
  go-app:
    build: ./backend/go-app
    container_name: go-app
    ports:
      - "8081:8080"
    networks:
      - app-network
  
  auth-service:
    build: ./backend/auth-service
    container_name: auth-service
    ports:
      - "8082:8080"
    networks:
      - app-network
  log-service:
    build: ./backend/log-service
    container_name: log-service
    ports:
      - "8083:8080"
    networks:
      - app-network

  payment-service:
    build: ./backend/payment-service
    container_name: payment-service
    ports:
      - "8084:8080"
    networks:
      - app-network

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8085:80"
    depends_on:
      - go-app
      - auth-service
      - log-service
      - payment-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge