version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # RabbitMQ 默认端口
      - "15672:15672"    # RabbitMQ 管理界面端口
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # 数据持久化
    environment:
      RABBITMQ_DEFAULT_USER: guest      # 设置默认用户名
      RABBITMQ_DEFAULT_PASS: guest   # 设置默认密码

volumes:
  rabbitmq_data:

