// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/order.proto

package microservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateOrderRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductIds           []string `protobuf:"bytes,2,rep,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderRequest) Reset()         { *m = CreateOrderRequest{} }
func (m *CreateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrderRequest) ProtoMessage()    {}
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f65b0626cc3aada8, []int{0}
}

func (m *CreateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderRequest.Unmarshal(m, b)
}
func (m *CreateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderRequest.Marshal(b, m, deterministic)
}
func (m *CreateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderRequest.Merge(m, src)
}
func (m *CreateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrderRequest.Size(m)
}
func (m *CreateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderRequest proto.InternalMessageInfo

func (m *CreateOrderRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateOrderRequest) GetProductIds() []string {
	if m != nil {
		return m.ProductIds
	}
	return nil
}

type CreateOrderResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	OrderId              string   `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderResponse) Reset()         { *m = CreateOrderResponse{} }
func (m *CreateOrderResponse) String() string { return proto.CompactTextString(m) }
func (*CreateOrderResponse) ProtoMessage()    {}
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f65b0626cc3aada8, []int{1}
}

func (m *CreateOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderResponse.Unmarshal(m, b)
}
func (m *CreateOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderResponse.Marshal(b, m, deterministic)
}
func (m *CreateOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderResponse.Merge(m, src)
}
func (m *CreateOrderResponse) XXX_Size() int {
	return xxx_messageInfo_CreateOrderResponse.Size(m)
}
func (m *CreateOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderResponse proto.InternalMessageInfo

func (m *CreateOrderResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateOrderResponse) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateOrderRequest)(nil), "CreateOrderRequest")
	proto.RegisterType((*CreateOrderResponse)(nil), "CreateOrderResponse")
}

func init() {
	proto.RegisterFile("proto/order.proto", fileDescriptor_f65b0626cc3aada8)
}

var fileDescriptor_f65b0626cc3aada8 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0xbf, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x95, 0x20, 0xe5, 0xc7, 0x05, 0x21, 0x70, 0x90, 0x08, 0x2c, 0x44, 0x99, 0x32, 0x39,
	0x12, 0x2c, 0xcc, 0xb0, 0x10, 0x06, 0x90, 0xcc, 0xc6, 0x12, 0x81, 0x7d, 0x83, 0x07, 0x70, 0xb8,
	0xb3, 0xfb, 0xf7, 0x57, 0x71, 0x5b, 0xa9, 0x55, 0xbb, 0xdd, 0x7b, 0xc3, 0xf7, 0xbd, 0x83, 0xab,
	0x99, 0x9c, 0x77, 0x83, 0x23, 0x83, 0x24, 0xe3, 0xdd, 0xbd, 0x83, 0x78, 0x21, 0xfc, 0xf6, 0xf8,
	0xb1, 0x94, 0x0a, 0xff, 0x03, 0xb2, 0x17, 0x37, 0x90, 0x07, 0x46, 0x9a, 0xac, 0x69, 0x92, 0x36,
	0xe9, 0x4b, 0x95, 0x2d, 0x71, 0x34, 0xe2, 0x1e, 0xaa, 0x99, 0x9c, 0x09, 0xda, 0x4f, 0xd6, 0x70,
	0x93, 0xb6, 0x67, 0x7d, 0xa9, 0x60, 0x5b, 0x8d, 0x86, 0xbb, 0x37, 0xa8, 0x0f, 0x78, 0x3c, 0xbb,
	0x3f, 0x46, 0xd1, 0x40, 0xce, 0x41, 0x6b, 0x64, 0x8e, 0xc0, 0x42, 0xed, 0xa2, 0xb8, 0x85, 0x22,
	0xee, 0x59, 0x5c, 0x69, 0x74, 0xe5, 0x31, 0x8f, 0xe6, 0xe1, 0x15, 0xce, 0x23, 0xe5, 0x13, 0x69,
	0x65, 0x35, 0x8a, 0x27, 0xa8, 0xf6, 0xd8, 0xa2, 0x96, 0xc7, 0xcb, 0xef, 0xae, 0xe5, 0x09, 0xfd,
	0xf3, 0xe5, 0xd7, 0x85, 0x1c, 0x7e, 0xad, 0x26, 0xc7, 0x1b, 0xd6, 0x4f, 0x16, 0xdf, 0x7f, 0x5c,
	0x07, 0x00, 0x00, 0xff, 0xff, 0x7f, 0x6c, 0x09, 0x9b, 0x13, 0x01, 0x00, 0x00,
}
