// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/payment.proto

package microservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PaymentRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount               float64  `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentRequest) Reset()         { *m = PaymentRequest{} }
func (m *PaymentRequest) String() string { return proto.CompactTextString(m) }
func (*PaymentRequest) ProtoMessage()    {}
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f344320e94f1899, []int{0}
}

func (m *PaymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentRequest.Unmarshal(m, b)
}
func (m *PaymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentRequest.Marshal(b, m, deterministic)
}
func (m *PaymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentRequest.Merge(m, src)
}
func (m *PaymentRequest) XXX_Size() int {
	return xxx_messageInfo_PaymentRequest.Size(m)
}
func (m *PaymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentRequest proto.InternalMessageInfo

func (m *PaymentRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *PaymentRequest) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type PaymentResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TransactionId        string   `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentResponse) Reset()         { *m = PaymentResponse{} }
func (m *PaymentResponse) String() string { return proto.CompactTextString(m) }
func (*PaymentResponse) ProtoMessage()    {}
func (*PaymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f344320e94f1899, []int{1}
}

func (m *PaymentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentResponse.Unmarshal(m, b)
}
func (m *PaymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentResponse.Marshal(b, m, deterministic)
}
func (m *PaymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentResponse.Merge(m, src)
}
func (m *PaymentResponse) XXX_Size() int {
	return xxx_messageInfo_PaymentResponse.Size(m)
}
func (m *PaymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentResponse proto.InternalMessageInfo

func (m *PaymentResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *PaymentResponse) GetTransactionId() string {
	if m != nil {
		return m.TransactionId
	}
	return ""
}

func init() {
	proto.RegisterType((*PaymentRequest)(nil), "PaymentRequest")
	proto.RegisterType((*PaymentResponse)(nil), "PaymentResponse")
}

func init() {
	proto.RegisterFile("proto/payment.proto", fileDescriptor_8f344320e94f1899)
}

var fileDescriptor_8f344320e94f1899 = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0x31, 0x4b, 0xc5, 0x30,
	0x14, 0x85, 0xc9, 0x1b, 0xfa, 0xf4, 0x82, 0x79, 0x8f, 0x08, 0x5a, 0x9c, 0x4a, 0x41, 0xe8, 0x94,
	0x82, 0xfd, 0x05, 0x0a, 0x0e, 0xdd, 0x4a, 0xdc, 0x5c, 0x24, 0xa6, 0x77, 0xc8, 0xd0, 0xa4, 0xe6,
	0x26, 0x82, 0xff, 0x5e, 0x9a, 0xd6, 0xa2, 0x8e, 0xdf, 0xb9, 0xf0, 0x9d, 0x73, 0xe1, 0x7a, 0x0e,
	0x3e, 0xfa, 0x76, 0xd6, 0x5f, 0x13, 0xba, 0x28, 0x33, 0xd5, 0x8f, 0xc0, 0x87, 0x35, 0x50, 0xf8,
	0x91, 0x90, 0xa2, 0xb8, 0x85, 0x63, 0x22, 0x0c, 0x6f, 0x76, 0x2c, 0x59, 0xc5, 0x9a, 0x4b, 0x55,
	0x2c, 0xd8, 0x8f, 0xe2, 0x06, 0x0a, 0x3d, 0xf9, 0xe4, 0x62, 0x79, 0xa8, 0x58, 0xc3, 0xd4, 0x46,
	0xb5, 0x82, 0xd3, 0xae, 0xa0, 0xd9, 0x3b, 0x42, 0x51, 0xc2, 0x91, 0x92, 0x31, 0x48, 0x94, 0x1d,
	0x17, 0xea, 0x07, 0xc5, 0x3d, 0xf0, 0x18, 0xb4, 0x23, 0x6d, 0xa2, 0xf5, 0x6e, 0x29, 0x39, 0xe4,
	0x92, 0xab, 0x5f, 0x69, 0x3f, 0x3e, 0x3c, 0xef, 0xb3, 0x5e, 0x30, 0x7c, 0x5a, 0x83, 0xa2, 0x03,
	0x3e, 0x04, 0xbf, 0x38, 0xb6, 0x83, 0x38, 0xc9, 0xbf, 0xcb, 0xef, 0xce, 0xf2, 0xdf, 0x8e, 0xa7,
	0xf3, 0x2b, 0x97, 0xed, 0x64, 0x4d, 0xf0, 0xb4, 0x6a, 0xde, 0x8b, 0xfc, 0x76, 0xf7, 0x1d, 0x00,
	0x00, 0xff, 0xff, 0xbf, 0x67, 0xd2, 0x91, 0x0d, 0x01, 0x00, 0x00,
}
